### ISSUE TITLE
"Video" is included as a category tag in the data, but there is no option to sort by video on the category page

### ISSUE THREAD

**Issue by ajunkins** [AlohaJarren/Sprint2-AVS-Project-MVP#40]
What it says on the tin. Multiple database entries contain "Video" as a category tag, but there is no category button for "Video" on any of the main catalog pages and no option to sort by Video.

**Comment by RJMNillo** [comment]
The "Video" category button is there, but you'll have to scroll to the right on the category Navbar.

Event Listener is now added to video, so users can now sort by video.
